# Hyprpaper configuration

# Preload wallpapers
preload = ~/Pictures/Wallpapers/aurora-borealis-night-sky-silhouette-nature-scenery-8K-162.jpg
preload = ~/Pictures/Wallpapers/autumn-forest-nature-scenery-mountain-45-8K.jpg
preload = ~/Pictures/Wallpapers/mountain-lake-nature-landscape-scenery-8K-161.jpg
preload = ~/Pictures/Wallpapers/mountain-landscape-scenery-8K-160.jpg
preload = ~/Pictures/Wallpapers/mountain-landscape-trees-nature-scenery-8K-158.jpg
preload = ~/Pictures/Wallpapers/mountain-nature-lake-landscape-scenery-8K-152.jpg
preload = ~/Pictures/Wallpapers/mountain-peak-nature-landscape-scenery-46-8K.jpg
preload = ~/Pictures/Wallpapers/night-sky-stars-horizon-scenery-8K-166.jpg
preload = ~/Pictures/Wallpapers/ocean-waves-nature-scenery-8K-167.jpg
preload = ~/Pictures/Wallpapers/planet-earth-space-52-8k.jpg
preload = ~/Pictures/Wallpapers/planet-earth-space-8K-159.jpg
preload = ~/Pictures/Wallpapers/red-fox-winter-snow-52-8K.jpg
preload = ~/Pictures/Wallpapers/sea-sunset-sky-clouds-seascape-natures-scenery-8K-153.jpg
preload = ~/Pictures/Wallpapers/star-night-sky-scenery-silhouette-8K-102.jpg
preload = ~/Pictures/Wallpapers/stars-night-sky-silhouette-scenery-8K-99.jpg
preload = ~/Pictures/Wallpapers/sunset-beach-sea-horizon-scenery-8K-165.jpg
preload = ~/Pictures/Wallpapers/sunset-sky-clouds-scenery-8K-166.jpg

# Set wallpaper for all monitors (handles PBP resolution changes)
wallpaper = ,~/Pictures/Wallpapers/ocean-waves-nature-scenery-8K-167.jpg

# Disable splash
splash = false

# Enable IPC
ipc = on
